### ISSUE TITLE
Create ~/.config directory for www-data

### ISSUE THREAD

**Issue by iVegas** [wodby/drupal-php#62]
In cases when 3-rd party libraries that executed via PHP, `www-data` user should be able to store configurations of 3-rd party library.

Expected result: `/home/www-data/.config` has `700` mode and `www-data` user able to write data there.

Current result: `/home/www-data/.config` not exists 

P.S.: Wondering maybe this issue related to the `base-php` image

**Comment by csandanov** [comment]
Thank you for reporting this, there was an issue in wodby/php image – `/home/www-data` was owned by `wodby` user instead of `www-data`. Fixed now and available as a part of [4.9.2](https://github.com/wodby/drupal-php/releases/tag/4.9.2) stability tag, you now should be able to create `~/.config` from `www-data` user
