### ISSUE TITLE
Composer 2.0.*

### ISSUE THREAD

**Issue by mfradcourt** [wodby/drupal-php#76]
Could you create a tag for composer 2.0 which has been released on 24 of October. You may also consider tagging a version with composer 1 if it makes sense to you.

Since composer is added to the drupal-php image during the build process, and, the new default version of composer is 2.0.*, simply running the pipeline should do the trick?

**Comment by kevinquillen** [comment]
Composer 2 is way faster on Drupal 8/9. I just tried it. Despite it using the installer url for Composer, the PHP tags still seem to ship with Composer 1. Has there been a tagged image since Oct 24th?

I was able to get around it on a test project and try out Composer 2 with:

```
ARG PHP_TAG
FROM wodby/drupal-php:${PHP_TAG}
USER root
RUN composer self-update --2
USER wodby
```

The speed is much much better (especially combined with Mutagen) and want to use it right away. For now it seems like I need to use my own Dockerfile to get it.

Will there be an update this week?

**Comment by csandanov** [comment]
Currently tests fail with composer 2 because drupal console does not yet support it https://github.com/hechoendrupal/drupal-console-extend-plugin/issues/23

**Comment by kevinquillen** [comment]
I usually add Drush via Composer to projects and don't use Drupal Console at all. Is it wise for this image to couple itself to Drupal Console? Commits are sporadic and as far as I understand it is not very active...

**Comment by csandanov** [comment]
latest and 4.19.0+ now come with composer 2.0
